In [1]:
import torch

#### 2.3.1 Scalars

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

#### 2.3.2 Vectors

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

#### 2.3.3 Matrices

In [7]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [9]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### 2.3.4 Tensors

In [10]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

#### 2.3.5 Basic Properties of Tensor Arithmetic

In [11]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [12]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

#### 2.3.6 Reduction

In [14]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [15]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [16]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [17]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [18]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [20]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

#### 2.3.7 Non-Reducion Sum

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [22]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [23]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

#### 2.3.8 Dot Products

In [24]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [25]:
torch.sum(x * y)

tensor(3.)

#### 2.3.9 Matrix-Vector Products

In [26]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

#### 2.3.10 Matrix-Matrix Multiplication

In [27]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

#### 2.3.11 Norms

In [28]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [29]:
torch.abs(u).sum()

tensor(7.)

In [30]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

##### exercise_1 and exercise_2
Write matrices into combinations of elements, and the result is obvious.

##### exercise_3
Since (A + A.T).T = A.T + (A.T).T = A.T + A = A + A.T, (A+A.T) is always symmetic.

In [43]:
# exercise_4
## 2 * 3 * 4 probably?
len(X)

2

In [41]:
# exercise_5
## The first axis.

# exercise_6
A, A / A.sum(axis=1,  keepdim=True)
## It ends up error. A is a 2*3 tensor, and A.sum(axis=1) is a vector.
## Python could not broadcast such culculate. 
## Add keepdim=True behand axis=1 will help.

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [34]:
# exercise_7
## Could not. We have to move along the street.

# exercise_8
## Each output is a 2-order tensor.
exe_8 = torch.arange(24).reshape(2, 3, 4)
exe_8.sum(axis=0), exe_8.sum(axis=1), exe_8.sum(axis=2)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [38]:
# exercise_9
import numpy as np
exe_9_1 = torch.arange(24).reshape(2, 3, 4)
exe_9_2 = torch.arange(120).reshape(2, 3, 4, 5)

np.linalg.norm(exe_9_1), np.linalg.norm(exe_9_2)

(65.75712889109438, 754.2015645701088)

##### exercise_10
It varies.  
Generally, producting a m*n and a n*k tensor requires n*(m*k) times of product and m*k times of summation.  
If (AB)C requires m*k*(n+t) times of production, A(BC) requires n*t*(m+k) times of production.  
So (AB)C (2^31) calculates quicker tnan A(BC) (2^40).  

##### exercise_11
The difference occurs when C is transposed. Commonly, A(C.T) is better.  
Commonly, a tensor is more likely to be memoried line by line.  
When calculating AB, B is accessed column by column, and it takes time.  
On the contrary, when calculating A(C.T), C is accessed line by line, which is constant, and it saves time.  
Without cloning memory, C and B will refer to same piece of place.  
It saves sapce, but C's change will influence B, vise versa.  

##### exercise_12
Three dimensionalities, the size of result will be 3 * 100 * 200.  
B == [A,B,C](2,:,:) == [A,B,C](2)